import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TRPCProvider } from "@/trpc/client";
import Navbar from "@/components/navbar/navbar";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import LayoutSidebar from "@/components/sidebar/layout-sidebar";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TRPCProvider>
          <SidebarProvider defaultOpen={true}>
            <LayoutSidebar />
            <div className='w-full'>
              <SidebarInset>
                <Navbar />
                {children}
                <Toaster richColors expand={true} visibleToasts={6} />
              </SidebarInset>
            </div>
          </SidebarProvider>
        </TRPCProvider>
      </body>
    </html>
  );
}
